#!/bin/bash

#Author: SxNade :: https://github.com/SxNade :: SxNade@protonmail.com

BGreen='\033[1;32m'
BRed='\033[1;31m'
NC='\033[0m'

echo "	----------------------"
echo -e "		sub53 ${BRed}v1.1a${NC}       "
echo "	----------------------"

echo -e "		SxNade\n"


find_subs() {
	curl https://crt.sh/?q=${1} | grep -o .*.${1} | awk -F "<TD>" '{print $2}' | awk -F "<BR>" '{print $1}' | sort -u > ${1}.txt
}


for domain in ${@}
do
	find_subs ${domain} &
done
wait

if [ ${?} -eq 0 ]
then
	clear
	echo -e "\n${BGreen}[+]${NC} subdomain Extraction Successfull..."
	for domain in ${@}
	do
		echo -e "\n[+] Results For ${BRed}${domain}${NC} ::: ${domain}.txt"
		echo -e "===================================================================================\n"

		for dmn in $(cat ${domain}.txt)
		do
			echo -e "${BGreen}-->${NC} ${dmn}"
		done
	done
fi


echo -e "\n${BGreen}[+]${NC} Filtering ${BRed}Alive${NC} subdomains now..\n"
echo -e "[*] Hit ${BRed}CTRL+C${NC} to stop or ${BGreen}wait${NC} 8 seconds to continue....."
sleep 15	#Yes Because you will take 7 seconds to read the alert above!


function filter() {
	for domain in $(cat $1)
	do
		host ${domain}
		if [ $? -eq 0 ]
		then
			echo ${domain} >> filtered.$1
		fi
	done
	sleep 2

}




for sub in $(ls *.txt)
do
	echo -e "[*] Filtering ${BRed}${sub}${NC} now...."
	filter ${sub}&
done
wait

echo -e "${BGreen}[+]${NC} Filtering ${BGreen}successfully${NC} completed...."
echo -e "\n${BGreen}[+]${BGreen} Filtered results have Been written to ${BRed}filtered${NC}.${BGreen}domain${NC}.txt files\n"
